name: logan_blaster
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - blast
  - biopython
  - pandas
  - openpyxl
  - requests
  - pip
  - setuptools
  - jq
  - rust
  - pip:
    - --editable .